pool:
  vmImage: 'ubuntu-16.04'

variables:
  imageName: 'sysdiglabs/dummy-vuln-app'
  tags: |
    latest
steps:
- bash: echo "Hello world"

- task: Docker@2
  displayName: Build image
  inputs:
    repository: $(imageName)
    command: build
    tags: $(tags)

#- script: inline_scan analyze -s https://secure.sysdig.com -k $(secureApiKey) $(imageName):latest
#  displayName: Scan image

#- task: Docker@2
#  inputs:
#    command: 'login'

#- task: Docker@2
#  inputs:
#    command: 'push'
#    tags: $(tags)
